CREATE TABLE "SiteConfig" (
  "id" TEXT NOT NULL DEFAULT 'main',
  "tickerSymbols" TEXT[] NOT NULL DEFAULT ARRAY['BTCUSDT', 'ETHUSDT', 'SOLUSDT', 'BNBUSDT', 'XRPUSDT']::TEXT[],
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,

  CONSTRAINT "SiteConfig_pkey" PRIMARY KEY ("id")
);
